### ISSUE TITLE
How to remove a credit listed twice

### ISSUE THREAD

**Issue by Garrettk41** [dracos/Theatricalia#25]
Some time ago, I added a credit to a theatricalia production and somehow or other added it again. Now it's the same credit listed twice back to back. I haven't been able to undo this mistake because deletion doesn't seem to be an option. Whenever I erase the actor and his character, I'm always told I have to specify the actor. How do I erase that second credit completely?

**Comment by dracos** [comment]
Apologies for the delay in this, I have removed the duplicate credit, thanks for adding some information to the site :)
